# Generated by Django 4.2.4 on 2023-08-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scraping_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_url", models.URLField()),
                ("keyword", models.CharField(max_length=255)),
                ("keyword_found", models.BooleanField(default=False)),
                ("relative_info", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="keyword",
        ),
        migrations.RemoveField(
            model_name="searchresult",
            name="website",
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
        migrations.DeleteModel(
            name="SearchResult",
        ),
        migrations.DeleteModel(
            name="Website",
        ),
    ]
